# Text that is displayed when calling the command
# Custom templates:
# <PLAYER> - player nickname
# <SPACE> - space
helpText:
  - "<RGB:1,1,1>~~~ <SPACE> <RGB:0.19,0.56,0.97> Help <SPACE> <RGB:1,1,1> ~~~"
  - "<RGB:1,1,1> Here's more information about the <SPACE> <RGB:0.4,0.5,0.8> server <LINE>"

# Text displayed before the list of server commands (appears after the text above)
commandsListText: "<RGB:1,1,1> Server commands:"

# Command Description
commandDescription: "Additional information about the server and commands"

# Text about insufficient rights
noRights: "<RGB:1,1,1> You do not have sufficient rights to view this command!"

# Text about missing command description
noCommands: "<RGB:1,1,1> Could not get a description for this command!"